### ISSUE TITLE
CRAN requires data  compression

### ISSUE THREAD

**Issue by dankelley** [TEOS-10/GSW-R#11]
The data file ``src/gsw_saar_data.c`` is 8.3M, which exceeds the limit for submission to CRAN (Comprehensive R Archive Network). Even though the resulting shared object is not excessive in size, this is still flagged as a submission-blocking problem, and so I am now working on a solution. Luckily, R packages can have "hooks" at load and unload time, and so I should be able use these to populate arrays (within ``malloc``ed storage) within the C code. I will try to do this with minimal changes to the C library, because every change made to the C library is a change that will need to be remade when that library changes.

**Comment by dankelley** [comment]
I've made some progress. It seems to work fine for me but I get one build NOTE, and I'd like to get rid of that because packages with "NOTE"s are frowned upon. The NOTE is as follows:
```
.onLoad: no visible binding for global variable ‘saar’
```

**Comment by dankelley** [comment]
Seems to be working now. In testing phase ... hope to resubmit 3rd version to CRAN today.

**Comment by fdelahoyde** [comment]
xz compression can get it down to 1.8M.

**Comment by PaulMBarker** [comment]
I am working on making a netcdf file to replace the ascii file that is currently used as the data file.

Paul.
________________________________

**Comment by dankelley** [comment]
Fixed, according to testing (a) within the package build; (b) within the oce package build; (c) in OAR.

Although I'm closing the issue, I plan to continue testing (for this and generally) for a day or so before CRAN submission.
