### ISSUE TITLE
handle updated TEOS-10 formulae

### ISSUE THREAD

**Issue by dankelley** [TEOS-10/GSW-R#12]
TEOS-10 has been updated. So far, the code is only available in matlab, but when it becomes available in C, it would make sense to incorporate this into the ``gsw`` R package.

At the moment, the ``gsw`` help pages that link to the TEOS-10 function webpages are still working (based on ``R CMD check --as-cran gsw_1.0-4.tar.gz`` with newly-build tarball). It seems that no URLs were made obsolete. However, the contents have changed. I don't think this is a huge problem because the TEOS-10 webpages clearly designate the order of the polynomial used, and so do the ``gsw`` help pages.

To satisfy my curiosity, I did a somewhat random and very isolated test. The results, shown below, suggest that (again, in this particular test) the new formula for density will yield changes that are swamped by density variations resulting from altering salinity at the limit of measurement.

First, 
```r
gsw_sigma0(34.7118, 28.8099) # 21.798411276610750
```
(where the comment is the value stated in the old TEOS-10 docs) yields
```
[1] 21.79841
```
yielding fractional change in density with change in formulation:
```r
2*(21.79841-21.798411276610750)/(21.79841+ 21.798411276610750)
```
being
```
[1] -5.85644e-08
```
which seems quite small. To get some context, lets add a tiny bit to ``SA`` (smaller than experimental uncertainty, I think)
```r
gsw_sigma0(34.7118+0.0005, 28.8099) # 21.798411276610750
```
from which we get
```
[1] 21.79878
```
Expressed as fractional change
```r
0.5*(21.79878-21.798411276610750)/(21.79878+ 21.798411276610750)
```
this data-perturbation yields density fractional change
```
[1] 4.228752e-06
```
which is about 80 times the fractional change associated with the algorithmic improvement.

**Comment by dankelley** [comment]
For further context on this, I looked up the [SBE 911 ctd specs](http://www.seabird.com/sbe911plus-ctd). They state an accuracy for conductivity of plus/minus 0.0003 S/m. To get an idea of the change in salinity, I did as follows.
```r
> library(gsw)
> swSCTp(4,15,100,conductivityUnit="S/m")
[1] 32.31857
> swSCTp(4+0.0003,15,100,conductivityUnit="S/m")
[1] 32.32127
```

Thus, it looks as though the error in Practical Salinity is about 0.003.  This is 10X the uncertainty assumed above. This suggests that -- at least for this example -- the density change associated with the switch in gsw formula will be 4000 times smaller than the uncertainty in density value for measured data.

**Comment by richardsc** [comment]
Note that version 3.05 of the [GSW-C](https://github.com/TEOS-10/GSW-C) has been pushed, so we could start work any time merging the new C functions into GSW-R.

**Comment by fdelahoyde** [comment]
SeaBird conductivity sensors are calibrated by comparing salinities calculated
from conductivity measurements to salinities measured by a laboratory
salinometer (typically a Guildline Autosal which has an accuracy of +/- 0.002
PSU).  The precision of the SBE sensor is about an order of magnitude better
than the reported accuracy.

Frank
--
	            Frank Delahoyde | Phone: 858.534.9562
        Shipboard Technical Support | Computing Resources
Scripps Institution of Oceanography | Nimitz Marine Facility
               297 Rosecrans Street |
               San Diego, Ca. 92106 | fdelahoyde@ucsd.edu

**Comment by dankelley** [comment]
Hi Frank. Any advice on when we should incorporate the new C code for the R version? As noted in these github comments, there's a fair bit of inertia at CRAN, the repository for R packages, so we'd want to be fairly sure things are stable before making a release.  My teaching starts in 2 days, so I'd be pretty happy to wait a few weeks until that settles a little.

Actually, the largest part of the work will be redoing all the documentation and test code. R is really big on that. The way we did that was by cut/paste from the GSW webpages, with manual alterations to change matlab to R. That is a bit slow, but these self-tests are one of the best things about R packaging.

**Comment by fdelahoyde** [comment]
Hi Dan,

I believe the code is stable, or at least having the same bugs as the Fortran 90
version.  Paul Barker has yet to put it on teos-10.org though, so you might want
to wait for that to happen.

Frank

**Comment by dankelley** [comment]
I'm opening a new, better-titled issue for the transition, and closing this one.
