### ISSUE TITLE
consider TravisCI inclusion in README

### ISSUE THREAD

**Issue by dankelley** [TEOS-10/GSW-R#13]
A lot of R packages hosted on GitHub are starting to use Travis CI as a quality demonstrator in their README files.  It looks [quite easy](http://docs.travis-ci.com/user/languages/r/) and the checks in gsw are very fast, so I propose to do that. @richardsc - any objection?

**Comment by richardsc** [comment]
Sounds good to me. I have only a passing understanding of what Travis CI does, but more checks are always good!

**Comment by dankelley** [comment]
Done
