### ISSUE TITLE
305 branch again has thousands of compilation warnings

### ISSUE THREAD

**Issue by dankelley** [TEOS-10/GSW-R#15]
Oh, should have guessed this. Rstudio uses a makefile method to avoid recompiling things if the .c file hasn't changed. So all those (5000 or so) warnings are actually still there. I had thought they went away.

I need to figure this out, because CRAN is not going to accept a package with thousands of compilation warnings.

Below are a few of the warnings.
```
clang -I/Library/Frameworks/R.framework/Resources/include -DNDEBUG  -I/usr/local/include -I/usr/local/include/freetype2 -I/opt/X11/include   --pedantic -fPIC  -Wall -mtune=core2 -g -O2  -c gsw_oceanographic_toolbox.c -o gsw_oceanographic_toolbox.o
gsw_oceanographic_toolbox.c:84:2: warning: unused variable 'delj' [-Wunused-variable]
        GSW_SAAR_DATA;
        ^
./gsw_internal_const.h:395:26: note: expanded from macro 'GSW_SAAR_DATA'
int     deli[4] = {0,1,1,0}, delj[4] = {0,0,1,1}, npan = 6; \
                             ^
gsw_oceanographic_toolbox.c:84:2: warning: unused variable 'deli' [-Wunused-variable]
./gsw_internal_const.h:395:5: note: expanded from macro 'GSW_SAAR_DATA'
int     deli[4] = {0,1,1,0}, delj[4] = {0,0,1,1}, npan = 6; \
        ^
gsw_oceanographic_toolbox.c:242:2: warning: unused variable 'pa2db' [-Wunused-variable]
        GSW_TEOS10_CONSTANTS;
        ^
./gsw_internal_const.h:12:2: note: expanded from macro 'GSW_TEOS10_CONSTANTS'
        pa2db = 1.0e-4, \
        ^
gsw_oceanographic_toolbox.c:243:2: warning: unused variable 'h211' [-Wunused-variable]
        GSW_SPECVOL_COEFFICIENTS;
        ^
./gsw_internal_const.h:263:2: note: expanded from macro 'GSW_SPECVOL_COEFFICIENTS'
        h211 = -4.35926785610e-5, \
        ^
gsw_oceanographic_toolbox.c:243:2: warning: unused variable 'c005' [-Wunused-variable]
./gsw_internal_const.h:174:2: note: expanded from macro 'GSW_SPECVOL_COEFFICIENTS'
        c005 =  1.17681023580e-8, \
        ^
```

**Comment by dankelley** [comment]
I think a lot of the warnings stem from using a single macro, and it's only used a few times, so I'll try expanding the relevant parts of the macro with hard-wired code.
```bash
$ git grep DATA
gsw_oceanographic_toolbox.c:    GSW_SAAR_DATA;
gsw_oceanographic_toolbox.c:    GSW_BALTIC_DATA;
gsw_oceanographic_toolbox.c:    GSW_BALTIC_DATA;
gsw_saar.c:     GSW_SAAR_DATA;
gsw_saar.c:     GSW_SAAR_DATA;

```

**Comment by dankelley** [comment]
Actually, there are lots of these macros for variable definition, e.g. below; I don't see it being helpful to expand them in place. Another option may be to move them all to the top of the .c file, on the assumption that some function must use each of these variables, or else they wouldn't be defined.
```bash
$ git grep GSW_TEOS10_CONSTANTS | wc
      86     173    4394
```

**Comment by dankelley** [comment]
Just checked with winbuilder, since I was hoping for a more relaxed syntax checking, but no luck; a link is http://win-builder.r-project.org/L56dcSW6rtA1/00install.out although that will go away after 72 hours.

**Comment by dankelley** [comment]
As a test, I hand-tweaked ``src/gsw_saar.c``, to remove it's dozen or so warnings. It's a fair bit of work. Here's what is involved for another file:
```bash
clang -I/Library/Frameworks/R.framework/Resources/include -DNDEBUG  -I/usr/local/include -I/usr/local/include/freetype2 -I/opt/X11/include   --pedantic -fPIC  -Wall -mtune=core2 -g -O2  -c gsw_oceanographic_toolbox.c -o gsw_oceanographic_toolbox.o|wc warning
5259
```

**Comment by fdelahoyde** [comment]
Hi Dan,

I've cleaned up the C distribution on github.  You should be able to compile
with no warnings.

Frank

**Comment by dankelley** [comment]
Thanks, Frank! This works great on my box (osx, using clang) and a windows build server (using gcc). Dan.

**Comment by fdelahoyde** [comment]
It may break if you use a compiler other than gcc (or compatibles such as Macosx
clang).

Frank

**Comment by dankelley** [comment]
FYI, it's fine on clang (that's what my machine uses). Acceptance in the R repository requires "quiet" compiles on a variety of machines, so I may still have problems.  At least now I have a clear list of unused things, so I can #ifdef them out if the R repository committee requires it. I'm not too clear on why those things are defined, if they are not to be used.

**Comment by fdelahoyde** [comment]
Actually some of them are used.  One of the changes that was made to the Fortran
90 toolkit was to compartmentalize frequently used constants into modules (sort
of like Python modules) so that they aren't repeated throughout the code.  Since
I'm trying to keep the C toolkit close to the Fortran 90 codebase I did
something similar via macro expansion (from gsw_internal_const.h) with the
unfortunate but acceptable side effect of defining some variables that aren't
always used.  My fix to quiet the warnings was to define an UNUSED macro that
directs GNU C compilers not to complain about variables that aren't used when
they are in a variable declaration statement beginning with it.

Frank

**Comment by dankelley** [comment]
I understand.  I checked on the R build machines, and they mostly use GNU or Clang compilers, so your UNUSED macro will work fine. The only exception is two Solaris compilers.  I guess if those compilers check for unused, then I'll have to think some more about this.  (Possibly a solution is to define these items as elements of a structure, so then if any element of the structure is used in a function, then the compiler will be okay.)
