### ISSUE TITLE
Update GSW-R to version 3.05

### ISSUE THREAD

**Issue by richardsc** [TEOS-10/GSW-R#20]
The current CRAN version of GSW is 3.03 (from January 2015). I think it is time to start implementing the version 3.05 files for a new release.

This issue can be used to track issues/progress towards this goal. Any sense of a timeline @dankelley ? I'm thinking it would be nice to have an updated package by the end of 2016. This might also coincide with an updated oce.

> DK edit: I am putting a checklist below, which I originally had within a separate comment. I moved it here so that an overall summary of issues would then tell us how far we are along in the conversion process, by counting checked and unchecked boxes. NOTE: the case in the function names given in the checklist is not always right.

- ~~gsw_add_barrier~~ (a utility function, not wrapped to R)
- ~~gsw_add_mean~~ (a utility function, not wrapped to R)
- [x] gsw_adiabatic_lapse_rate_from_ct
- [x] gsw_adiabatic_lapse_rate_ice
- [x] gsw_alpha
- [x] gsw_alpha_on_beta
- [x] gsw_alpha_wrt_t_exact
- [x] gsw_alpha_wrt_t_ice
- [x] gsw_beta
- [x] gsw_beta_const_t_exact
- [x] gsw_C_from_SP
- [x] gsw_cabbeling
- [x] gsw_chem_potential_water_ice
- [x] gsw_chem_potential_water_t_exact
- [x] gsw_cp_ice
- [x] gsw_cp_t_exact
- [x] gsw_CT_first_derivatives 
- [x] gsw_CT_first_derivatives_wrt_t_exact
- [x] gsw_CT_freezing
- [x] gsw_CT_freezing_first_derivatives
- [x] gsw_CT_freezing_first_derivatives_poly
- [x] gsw_CT_freezing_poly
- [x] gsw_CT_from_enthalpy
- [x] gsw_CT_from_enthalpy_t_exact
- [x] gsw_CT_from_enthalpy_ice
- [x] gsw_CT_from_entropy
- [x] gsw_CT_from_pt
- [x] gsw_CT_from_rho
- [x] gsw_CT_from_t
- [x] gsw_CT_maxdensity
- [x] gsw_CT_second_derivatives
- ~~~gsw_deltaSA_atlas~~~ not available in C library
- [x] gsw_deltaSA_from_SP
- [x] gsw_dilution_coefficient_t_exact
- [x] gsw_dynamic_enthalpy
- [x] gsw_enthalpy
- [x] gsw_enthalpy_CT_exact
- [x] gsw_enthalpy_diff
- [x] gsw_enthalpy_first_derivatives *Problem with HTML docs and therefore check values*
- [x] gsw_enthalpy_first_derivatives_CT_exact
- [x] gsw_enthalpy_ice
- [x] gsw_enthalpy_second_derivatives
- [x] gsw_enthalpy_second_derivatives_CT_exact
- ~~~gsw_enthalpy_sso_0~~~ internal utility function
- [x] gsw_enthalpy_t_exact
- [x] gsw_entropy_first_derivatives
- [x] gsw_entropy_from_pt
- [x] gsw_entropy_from_t
- [x] gsw_entropy_ice (see issue #25)
- ~~~gsw_entropy_part~~~ internal utility function
- ~~~gsw_entropy_part_zerop~~~ internal utility function
- [x] gsw_entropy_second_derivatives
- [x] gsw_fdelta
- [x] gsw_frazil_properties
- [x] gsw_frazil_properties_potential
- [x] gsw_frazil_properties_potential_poly
- [x] gsw_frazil_ratios_adiabatic
- [x] gsw_frazil_ratios_adiabatic_poly
- [x] gsw_geo_strf_dyn_height
- [x] gsw_geo_strf_dyn_height_pc
- [x] gsw_gibbs
- [x] gsw_gibbs_ice
- ~~~gsw_gibbs_ice_part_t~~~ internal utility function
- ~~~gsw_gibbs_ice_pt0~~~ internal utility function
- ~~~sw_gibbs_ice_pt0_pt0~~~ internal utility function
- ~~~gsw_gibbs_pt0_pt0~~~ internal utility function
- [x] gsw_grav
- [x] gsw_helmholtz_energy_ice
- ~~~gsw_hill_ratio_at_sp2~~~ *utility function, not documented in matlab*
- [x] gsw_ice_fraction_to_freeze_seawater
- [x] gsw_internal_energy
- [x] gsw_internal_energy_ice
- [x] gsw_ipv_vs_fnsquared_ratio
- [x] gsw_kappa
- [x] gsw_kappa_const_t_ice
- [x] gsw_kappa_ice
- [x] gsw_kappa_t_exact
- [x] gsw_latentheat_evap_ct
- [x] gsw_latentheat_evap_t
- [x] gsw_latentheat_melting
- ~~~gsw_linear_interp_SA_CT~~~ not available in C library
- [x] gsw_melting_ice_equilibrium_SA_CT_ratio
- [x] gsw_melting_ice_equilibrium_SA_CT_ratio_poly
- [x] gsw_melting_ice_into_seawater
- [x] gsw_melting_ice_SA_CT_ratio
- [x] gsw_melting_ice_SA_CT_ratio_poly
- [x] gsw_melting_seaice_equilibrium_SA_CT_ratio
- [x] gsw_melting_seaice_equilibrium_SA_CT_ratio_poly
- [x] gsw_melting_seaice_into_seawater
- ~~~gsw_melting_seaice_SA_CT_ratio~~~ duplicate function: see https://github.com/TEOS-10/GSW-C/issues/6
- ~~~gsw_melting_seaice_SA_CT_ratio_poly~~~ duplicate function: see https://github.com/TEOS-10/GSW-C/issues/6
- [x] gsw_nsquared
- [x] gsw_pot_enthalpy_from_pt_ice
- [x] gsw_pot_enthalpy_from_pt_ice_poly
- [x] gsw_pot_enthalpy_ice_freezing
- [x] gsw_pot_enthalpy_ice_freezing_first_derivatives
- [x] gsw_pot_enthalpy_ice_freezing_first_derivatives_poly
- [x] gsw_pot_enthalpy_ice_freezing_poly
- [x] gsw_pot_rho_t_exact
- [x] gsw_pressure_coefficient_ice
- [x] gsw_pressure_freezing_ct
- ~~~gsw_pt0_cold_ice_poly~~~ *Not listed at http://www.teos-10.org/pubs/gsw/html/gsw_contents.html*
- [x] gsw_pt0_from_t
- [x] gsw_pt0_from_t_ice
- [x] gsw_pt_first_derivatives 
- [x] gsw_pt_from_CT
- [x] gsw_pt_from_entropy
- [x] gsw_pt_from_pot_enthalpy_ice
- [x] gsw_pt_from_pot_enthalpy_ice_poly
- ~~~gsw_pt_from_pot_enthalpy_ice_poly_dh~~~ *Not listed at http://www.teos-10.org/pubs/gsw/html/gsw_contents.html*
- [x] gsw_pt_from_t
- [x] gsw_pt_from_t_ice
- [x] gsw_pt_second_derivatives 
- [x] gsw_rho
- [x] gsw_rho_alpha_beta 
- [x] gsw_rho_first_derivatives
- [x] gsw_rho_first_derivatives_wrt_enthalpy 
- [x] gsw_rho_ice
- [x] gsw_rho_second_derivatives
- [x] gsw_rho_second_derivatives_wrt_enthalpy
- [x] gsw_rho_t_exact
- ~~~gsw_rr68_interp_SA_ct~~~ *internal utility function*
- [x] gsw_SAAR (but note that in_ocean is broken)
- ~~~gsw_SA_freezing_estimate~~~ *Not listed at http://www.teos-10.org/pubs/gsw/html/gsw_contents.html*
- [x] gsw_SA_freezing_from_CT
- [x] gsw_SA_freezing_from_CT_poly
- [x] gsw_SA_freezing_from_t
- [x] gsw_SA_freezing_from_t_poly
- [x] gsw_SA_from_rho
- [x] gsw_SA_from_SP
- [x] gsw_SA_from_SP_baltic
- [x] gsw_SA_from_SStar
- ~~~gsw_SA_p_inrange~~~ *Not listed at http://www.teos-10.org/pubs/gsw/html/gsw_contents.html*
- [x] gsw_seaice_fraction_to_freeze_seawater
- [x] gsw_sigma0
- [x] gsw_sigma1
- [x] gsw_sigma2
- [x] gsw_sigma3
- [x] gsw_sigma4
- [x] gsw_sound_speed
- [x] gsw_sound_speed_ice
- [x] gsw_sound_speed_t_exact
- [x] gsw_SP_from_C
- [x] gsw_SP_from_SA
- [x] gsw_SP_from_SA_baltic
- [x] gsw_SP_from_SK
- [x] gsw_SP_from_SR
- [x] gsw_SP_from_SStar
- [x] gsw_specvol
- [x] gsw_specvol_alpha_beta
- [x] gsw_specvol_anom_standard
- [x] gsw_specvol_first_derivatives
- [x] gsw_specvol_first_derivatives_wrt_enthalpy
- [x] gsw_specvol_ice
- [x] gsw_specvol_second_derivatives 
- [x] gsw_specvol_second_derivatives_wrt_enthalpy
- ~~~gsw_specvol_sso_0~~~ *internal utility function*
- [x] gsw_specvol_t_exact
- [x] gsw_spiciness0
- [x] gsw_spiciness1
- [x] gsw_spiciness2
- [x] gsw_SR_from_SP
- [x] gsw_SStar_from_SA
- [x] gsw_SStar_from_SP
- [x] gsw_t_deriv_chem_potential_water_t_exact
- [x] gsw_t_freezing
- ~~~gsw_t_freezing_exact~~~ *I think this is just gsw_t_freezing*
- [x] gsw_t_freezing_first_derivatives *coded but test values are not working*
- [x] gsw_t_freezing_first_derivatives_poly *coded but only tfreezing_p test values is working*
- [x] gsw_t_freezing_poly
- [x] gsw_t_from_ct
- [x] gsw_t_from_pt0_ice
- [x] gsw_thermobaric
- [x] gsw_turner_rsubrho
- ~~gsw_util_indx~~ (a utility function, not wrapped to R)
- ~~gsw_util_interp1q_int~~ (a utility function, not wrapped to R)
- ~~gsw_util_linear_interp~~ (a utility function, not wrapped to R)
- ~~gsw_util_sort_real~~ (a utility function, not wrapped to R)
- ~~gsw_util_xinterp1~~ (a utility function, not wrapped to R)
- [x] gsw_z_from_p

**Comment by dankelley** [comment]
Clark, yes, I think end of 2016 is reasonable, but I also think we should try to ensure that the code is "out there" for a long time before a CRAN submission, partly because there are a lot of people involved with GSW and a faulty release might be taken to reflect on them (even though it would really only reflect on the two of us, since the bugs would be in the wrappers).

I have not looked much at the changes for 3.05, but if they are significant, then it will be a fair bit of work to get all the test values working.  There are also some functions that I didn't put in before, e.g. spiciness, and some work will have to be done to cross-check between the functions we provide and those that are defined in the C code.

Luckily, I think we have some time to get things right, because we have *never* had an issue from anyone but you and me. So either (a) nobody is using this or (b) it all works well at the moment. I think the second is more likely true, and it is a testament to the clever design of the R build-test mechanism, and the generosity of the upstream GSW authors in providing test values.

**Comment by dankelley** [comment]
I revived an old branch named `305`. I propose that the transition work mainly be done in `305`, and that `develop` be used for non-305-related changes. (PS. I also merged some recent `master` changes into `develop`.)

**Comment by dankelley** [comment]
I checked `gsw_alpha` by looking at its help page. That page lists test values that match the values given at http://www.teos-10.org/pubs/gsw/html/gsw_alpha.html, which is stated to relate to the 3.05 version. And, of course, the test values in the `gsw_alpha` help page are checked during the building process.  This suggested to me that at least some of the functions must already be using the 3.05 version.

Then I looked in `src/gsw_oceanographic_toolbox.c` in the GSW-R sources, and it begins with
```
/*
**  $Id: gsw_oceanographic_toolbox.c,v ff74fd981dc9 2015/09/13 18:29:10 fdelahoyde $
**  $Version: 3.05.0-2 $
```
and that seems to be very clear. We are already using the 3.05 version. 

3. I checked https://github.com/TEOS-10/GSW-C/blob/master/gsw_oceanographic_toolbox.c and it starts as follows
```
/*
**  $Id: gsw_oceanographic_toolbox.c,v 9248219e2c8d 2016/08/29 23:43:19 fdelahoyde $
**  Version: 3.05.0-3
```
so there is a new version available.

**Conclusion** I will update to this new version (3.05-0-3) sometime in the next few weeks. The code shift is likely to be really quite easy (maybe 10 minutes to drop in the file and a few hours to figure out any requisite patches) but then the hard part will begin: (1) writing wrappers for any functions that are missing [maybe a couple of hours] and (2) going through each of the 60+ functions, to incorporate new check values, if there are any [a dozen hours, estimating 10 minutes per function to cut/paste from the webpages and reformat the matlab into R].

**Comment by dankelley** [comment]
I had a few minutes so I tentatively tried dropping in the C code, making a trivial change, and doing a build-check cycle. It works, as is. Since all the functions have test values (I think ... I'll check on that), it seems there is only one task remaining, which is to look in the `.h` file to see if there are any interesting functions that have been missed (like spiciness had been missed).

**Comment by dankelley** [comment]
I updated a few more things, and also I updated `README_developer.md` to show how to update when upstream changes occur. I think the remaining task is to check that we haven't missed any functions. I'll have a look at that later this week (and I'll put into `README_developer.md` some notes on the `grep` commands used to do such detective work).

**Comment by PaulMBarker** [comment]
Gsw 3.05 is available for Matlab, fortran and c.

Let me know if you find any bad test values in the help pages as I have to make them by hand


-------- Original message --------

**Comment by dankelley** [comment]
Below is a checklist of functions in the C library, as inferred with `developer/create_c_checklist.R` in the `305` branch of the present repo. I will put check marks in the boxes as I check the functions for (a) wrapper status in R and (b) correctness of tests take from the matlab source and incorporated in the R docs. (Any other developer reading this should note that there will be no email notifications as I check these off. That's on purpose -- I don't see any need to repost again on this issue until I'm done.)
* [ ]  gsw_add_barrier
* [ ] gsw_add_mean
* [ ] gsw_adiabatic_lapse_rate_from_ct
* [ ] gsw_adiabatic_lapse_rate_ice
* [ ] gsw_alpha
* [ ] gsw_alpha_on_beta
* [ ] gsw_alpha_wrt_t_exact
* [ ] gsw_alpha_wrt_t_ice
* [ ] gsw_beta
* [ ] gsw_beta_const_t_exact
* [ ] gsw_c_from_sp
* [ ] gsw_cabbeling
* [ ] gsw_chem_potential_water_ice
* [ ] gsw_chem_potential_water_t_exact
* [ ] gsw_cp_ice
* [ ] gsw_cp_t_exact
* [ ] gsw_ct_first_derivatives 
* [ ] gsw_ct_first_derivatives_wrt_t_exact
* [ ] gsw_ct_freezing
* [ ] gsw_ct_freezing_exact
* [ ] gsw_ct_freezing_first_derivatives
* [ ] gsw_ct_freezing_first_derivatives_poly
* [ ] gsw_ct_freezing_poly
* [ ] gsw_ct_from_enthalpy
* [ ] gsw_ct_from_enthalpy_exact
* [ ] gsw_ct_from_entropy
* [ ] gsw_ct_from_pt
* [ ] gsw_ct_from_rho
* [ ] gsw_ct_from_t
* [ ] gsw_ct_maxdensity
* [ ] gsw_ct_second_derivatives
* [ ] gsw_deltasa_atlas
* [ ] gsw_deltasa_from_sp
* [ ] gsw_dilution_coefficient_t_exact
* [ ] gsw_dynamic_enthalpy
* [ ] gsw_enthalpy
* [ ] gsw_enthalpy_ct_exact
* [ ] gsw_enthalpy_diff
* [ ] gsw_enthalpy_first_derivatives
* [ ] gsw_enthalpy_first_derivatives_ct_exact
* [ ] gsw_enthalpy_ice
* [ ] gsw_enthalpy_second_derivatives
* [ ] gsw_enthalpy_second_derivatives_ct_exact
* [ ] gsw_enthalpy_sso_0
* [ ] gsw_enthalpy_t_exact
* [ ] gsw_entropy_first_derivatives
* [ ] gsw_entropy_from_pt
* [ ] gsw_entropy_from_t
* [ ] gsw_entropy_ice
* [ ] gsw_entropy_part
* [ ] gsw_entropy_part_zerop
* [ ] gsw_entropy_second_derivatives
* [ ] gsw_fdelta
* [ ] gsw_frazil_properties
* [ ] gsw_frazil_properties_potential
* [ ] gsw_frazil_properties_potential_poly
* [ ] gsw_frazil_ratios_adiabatic
* [ ] gsw_frazil_ratios_adiabatic_poly
* [ ] gsw_geo_strf_dyn_height
* [ ] gsw_geo_strf_dyn_height_pc
* [ ] gsw_gibbs
* [ ] gsw_gibbs_ice 
* [ ] gsw_gibbs_ice_part_t
* [ ] gsw_gibbs_ice_pt0
* [ ] gsw_gibbs_ice_pt0_pt0
* [ ] gsw_gibbs_pt0_pt0
* [ ] gsw_grav
* [ ] gsw_helmholtz_energy_ice
* [ ] gsw_hill_ratio_at_sp2
* [ ] gsw_ice_fraction_to_freeze_seawater
* [ ] gsw_internal_energy
* [ ] gsw_internal_energy_ice
* [ ] gsw_ipv_vs_fnsquared_ratio
* [ ] gsw_kappa
* [ ] gsw_kappa_const_t_ice
* [ ] gsw_kappa_ice
* [ ] gsw_kappa_t_exact
* [ ] gsw_latentheat_evap_ct
* [ ] gsw_latentheat_evap_t
* [ ] gsw_latentheat_melting
* [ ] gsw_linear_interp_sa_ct
* [ ] gsw_melting_ice_equilibrium_sa_ct_ratio
* [ ] gsw_melting_ice_equilibrium_sa_ct_ratio_poly
* [ ] gsw_melting_ice_into_seawater
* [ ] gsw_melting_ice_sa_ct_ratio
* [ ] gsw_melting_ice_sa_ct_ratio_poly
* [ ] gsw_melting_seaice_equilibrium_sa_ct_ratio
* [ ] gsw_melting_seaice_equilibrium_sa_ct_ratio_poly
* [ ] gsw_melting_seaice_into_seawater
* [ ] gsw_melting_seaice_sa_ct_ratio
* [ ] gsw_melting_seaice_sa_ct_ratio_poly
* [ ] gsw_nsquared
* [ ] gsw_pot_enthalpy_from_pt_ice
* [ ] gsw_pot_enthalpy_from_pt_ice_poly
* [ ] gsw_pot_enthalpy_ice_freezing
* [ ] gsw_pot_enthalpy_ice_freezing_first_derivatives
* [ ] gsw_pot_enthalpy_ice_freezing_first_derivatives_poly
* [ ] gsw_pot_enthalpy_ice_freezing_poly
* [ ] gsw_pot_rho_t_exact
* [ ] gsw_pressure_coefficient_ice
* [ ] gsw_pressure_freezing_ct
* [ ] gsw_pt_first_derivatives 
* [ ] gsw_pt_from_ct
* [ ] gsw_pt_from_entropy
* [ ] gsw_pt_from_pot_enthalpy_ice
* [ ] gsw_pt_from_pot_enthalpy_ice_poly
* [ ] gsw_pt_from_pot_enthalpy_ice_poly_dh
* [ ] gsw_pt_from_t
* [ ] gsw_pt_from_t_ice
* [ ] gsw_pt_second_derivatives 
* [ ] gsw_pt0_cold_ice_poly
* [ ] gsw_pt0_from_t
* [ ] gsw_pt0_from_t_ice
* [ ] gsw_rho
* [ ] gsw_rho_alpha_beta 
* [ ] gsw_rho_first_derivatives
* [ ] gsw_rho_first_derivatives_wrt_enthalpy 
* [ ] gsw_rho_ice
* [ ] gsw_rho_second_derivatives
* [ ] gsw_rho_second_derivatives_wrt_enthalpy
* [ ] gsw_rho_t_exact
* [ ] gsw_rr68_interp_sa_ct
* [ ] gsw_sa_freezing_estimate
* [ ] gsw_sa_freezing_from_ct
* [ ] gsw_sa_freezing_from_ct_poly
* [ ] gsw_sa_freezing_from_t
* [ ] gsw_sa_freezing_from_t_poly
* [ ] gsw_sa_from_rho
* [ ] gsw_sa_from_sp
* [ ] gsw_sa_from_sp_baltic
* [ ] gsw_sa_from_sstar
* [ ] gsw_sa_p_inrange
* [ ] gsw_saar
* [ ] gsw_seaice_fraction_to_freeze_seawater
* [ ] gsw_sigma0
* [ ] gsw_sigma1
* [ ] gsw_sigma2
* [ ] gsw_sigma3
* [ ] gsw_sigma4
* [ ] gsw_sound_speed
* [ ] gsw_sound_speed_ice
* [ ] gsw_sound_speed_t_exact
* [ ] gsw_sp_from_c
* [ ] gsw_sp_from_sa
* [ ] gsw_sp_from_sa_baltic
* [ ] gsw_sp_from_sk
* [ ] gsw_sp_from_sr
* [ ] gsw_sp_from_sstar
* [ ] gsw_specvol
* [ ] gsw_specvol_alpha_beta
* [ ] gsw_specvol_anom_standard
* [ ] gsw_specvol_first_derivatives
* [ ] gsw_specvol_first_derivatives_wrt_enthalpy
* [ ] gsw_specvol_ice
* [ ] gsw_specvol_second_derivatives 
* [ ] gsw_specvol_second_derivatives_wrt_enthalpy
* [ ] gsw_specvol_sso_0
* [ ] gsw_specvol_t_exact
* [ ] gsw_spiciness0
* [ ] gsw_spiciness1
* [ ] gsw_spiciness2
* [ ] gsw_sr_from_sp
* [ ] gsw_sstar_from_sa
* [ ] gsw_sstar_from_sp
* [ ] gsw_t_deriv_chem_potential_water_t_exact
* [ ] gsw_t_freezing
* [ ] gsw_t_freezing_exact
* [ ] gsw_t_freezing_first_derivatives
* [ ] gsw_t_freezing_first_derivatives_poly
* [ ] gsw_t_freezing_poly
* [ ] gsw_t_from_ct
* [ ] gsw_t_from_pt0_ice
* [ ] gsw_thermobaric
* [ ] gsw_turner_rsubrho
* [ ] gsw_util_indx
* [ ] gsw_util_interp1q_int
* [ ] gsw_util_linear_interp
* [ ] gsw_util_sort_real
* [ ] gsw_util_xinterp1
* [ ] gsw_z_from_p

**Comment by dankelley** [comment]
In `develop` commit 9a59f56d050d61828ae3e0266c9e0819f6414801, I have handled all the functions named in the checklist in the first comment for this issue. There are still cases in which the values do not agree with official values on the HTML webpages (at http://www.teos-10.org/pubs/gsw/html), and this issue will be left open until there is agreement between the two.

**Comment by PaulMBarker** [comment]
It will be about a week til I can update the TEOS-10 website, as my internet connection is down to just 1 mbps.

**Comment by dankelley** [comment]
@richardsc -- I think this issue has been addressed^[1]. I'll leave it to you to decide whether to close it.

[1]: I do not mean that things are perfect, but merely that the R functions now use the up-to-date version of the C code, which is mainly 3.05, so far as I can tell. There are some wrinkles yet to be smoothed out, but we have issues for each of them, and so there seems to be no need to keep the present issue open. And we can get new issues, e.g. as regards clarity of the documentation (most importantly, the phrasing of the roxygen templates), but, again, that's not an argument to keep the present issue open. Thanks!

**Comment by richardsc** [comment]
Agreed. I'll close and we'll deal with new issues as they arise.
