### ISSUE TITLE
gsw ver 1.0-3: Inconsistent handling of input data with NA values from gsw_SA_from_SP & gsw_CT_from_pt

### ISSUE THREAD

**Issue by Abulos** [TEOS-10/GSW-R#21]
I am using R version 3.3.2 (2016-10-31)

When I have an `NA` value in my data I noticed:
```R
gsw_SA_from_SP returns NA
gsw_CT_from_pt returns NaN
```
This seems inconsistent. Assume they should both return `NA`?

Great to have gsw in R! Thankyou!

I am new to Github. Hope I have done this right.

Regards
Abe

**Comment by dankelley** [comment]
Yes, you did it perfectly (although I added in triple-backtick sequences to make your code look like code). I'll look at this later today -- of course, you are right, and both should give `NA`. Thanks. Dan.

**Comment by dankelley** [comment]
I wonder if you can (a) tell us how you installed R (i.e. from CRAN or from this website) and (b) what you get on the following test code (which seems OK to me). Thanks again!
```R
library(gsw)
print(gsw_SA_from_SP(SP=c(35, NA), p=c(100,100), longitude=c(-30,-30), latitude=c(45,45)))
print(gsw_CT_from_pt(c(35, NA), pt=c(10,11)))
```
the above makes as below with the github version.
```R
[1] 35.1658      NA
[1] 9.992855       NA
```

**Comment by Abulos** [comment]
Installed R from CRAN. When I first reported the bug I was using R-studio but I have now tried it in R. Code below:

gsw    version 1.0-3 (installed using R-studio)

R version 3.3.2 (2016-10-31) -- "Sincere Pumpkin Patch"
Copyright (C) 2016 The R Foundation for Statistical Computing
Platform: x86_64-w64-mingw32/x64 (64-bit)

> library(gsw)
> gsw_CT_from_pt(c(35,NA), pt=c(20,20))
[1] 19.99802      NaN
> 
> gsw_CT_from_t(c(35,NA), t=c(20,20), p=c(10.1325,10.1325))
[1] 19.99615       NA

**Comment by dankelley** [comment]
I think this is addressed in the `develop` version, commit bd900b3d5e7a1eccaaeec815a96faaad318e50ca. If your machine is set up to build R packages (e.g. it must have a C compiler) then you can test this version by doing as below. If not, I could email you a pre-built OSX or a per-build Windows package ... just let me know.
```R
library(devtools)
install_github("TEOS-10/GSW-R", ref="develop")
```

@Abulos -- please try the above and post a comment on your findings.  Thanks!

**Comment by dankelley** [comment]
If you think the issue (as defined by its title) has been addressed, please close it. This comment is made when it seems that an issue has been addressed and that discussion has ceased. Please bear in mind that we work on issues *as defined by their titles*. Narrow-scoped titles help us to focus our development efforts, and benefit other oce users.

If you think the issue has not been addressed, please look through all the comments and write a new one after this, stating what still needs to be done.

If you see that the issue has meandered from the topic defined by its title, please consider closing this and opening a new issue.

Thanks!

**Comment by dankelley** [comment]
**Standardized comment.** This issue has been closed, since it seems to have been addressed, and since  discussion has stalled. The original reporter should feel free to reopen it, though, or to open new issues that might be related. Thanks.
