### ISSUE TITLE
confusion on "gsw_specvol_first_derivatives_wrt_enthalpy.html"

### ISSUE THREAD

**Issue by dankelley** [TEOS-10/GSW-R#30]
I am confused about http://www.teos-10.org/pubs/gsw/html/gsw_specvol_first_derivatives_wrt_enthalpy.html in which I see as follows (an aside: the C source uses a different name for the first variable):

        OUTPUT:

        v_SA_wrt_h  =  The first derivative of specific volume with respect to 
                    Absolute Salinity at constant CT & p.   
                                                 [ (m^3/kg)(g/kg)^-1 (J/kg)^-1 ]
        v_h  =  The first derivative of specific volume with respect to 
                    SA and CT at constant p.               [ (m^3/kg)(J/kg)^-1 ]

The units, the wording, and even the naming all confuse me a bit. I wonder if it's just me?

**Units**

The unit of `v_h` seems OK. $d(spec vol)/d(enthalpy)$ has unit (m^3/kg) / (J/kg) because “enthalpy” (really, either “mass-specific enthalpy”, or “specific enthalpy”, but that's a small detail) has unit J/kg. 

But the unit of `v_SA_wrt_h` suggests that we may have $d^2(spec vol)/d(SA)/d(enthalpy)$ so it’s not a “first derivative” as in the function name.

**Wording**

For `v_h`, I am drawing a blank as to what "The first derivative of specific volume with respect to SA and CT at constant p" means.

**Naming**

If my hypothesis on the meaning of `v_SA_wrt_h` is correct, should this maybe be called `v_SA_h` or something? I don't quite understand what "wrt" means.

I'm sorry if I'm just being dense, and I'm hoping this comment will help others.

**Comment by PaulMBarker** [comment]
The words for the output are not quite correct, they are correct in the description. I will fix this.

wrt = with respect to. This is included as the inputs to the function are SA,CT and p, not SA, h and p. 

 I need to think about the units.

**Comment by dankelley** [comment]
Fixed in `master` commit 11622590e2ad26fd587b3778baa15c3e9ca3726c by cleaning the R doc for `gsw_specvol_first_derivatives_wrt_enthalpy`
