### ISSUE TITLE
gsw_rho_second_derivatives_wrt_enthalpy() test values fail

### ISSUE THREAD

**Issue by dankelley** [TEOS-10/GSW-R#35]
@PaulMBarker -- I suspect the check values listed at

http://www.teos-10.org/pubs/gsw/html/gsw_rho_second_derivatives_wrt_enthalpy.html for

are incorrect.  In R I get as follows. Clark is getting the same things in Matlab; neither matches the values on teos-10.org

```R
> library(gsw) # must be installed from github to get latest version
> SA <- c(34.7118, 34.8915, 35.0256, 34.8472, 34.7366, 34.7324)
> CT <- c(28.8099, 28.4392, 22.7862, 10.2262,  6.8272,  4.3236)
> p <- c(      10,      50,     125,     250,     600,    1000)
> r <- gsw_rho_second_derivatives_wrt_enthalpy(SA, CT, p)
> data.frame(CT,SA,p,r)
       CT      SA    p            rho_SA_SA              rho_SA_h               rho_h_h
1 28.8099 34.7118   10 0.000207312267114544 -4.59053080088382e-07 -4.54213854637790e-10
2 28.4392 34.8915   50 0.000207065033523473 -4.60370569872258e-07 -4.55984900239309e-10
3 22.7862 35.0256  125 0.000191848346945039 -4.98605615416296e-07 -4.99870030989387e-10
4 10.2262 34.8472  250 0.000133182862881598 -6.42833108550132e-07 -6.28337767293403e-10
5  6.8272 34.7366  600 0.000116049034622904 -6.82091962941161e-07 -6.64021595759308e-10
6  4.3236 34.7324 1000 0.000102745309429078 -7.06793055445909e-07 -6.87367088752173e-10
```

**Comment by PaulMBarker** [comment]
I have redone the calculations for the help page, here are the new values.

SA = [34.7118; 34.8915; 35.0256; 34.8472; 34.7366; 34.7324;]
CT = [28.8099; 28.4392; 22.7862; 10.2262;  6.8272;  4.3236;]
p =  [     10;      50;     125;     250;     600;    1000;]

[rho_SA_SA_wrt_h, rho_SA_h, rho_h_h] = ...
                 gsw_rho_second_derivatives_wrt_enthalpy(SA,CT,p)

rho_SA_SA_wrt_h =

   1.0e-03 *

   0.207312267114544
   0.207065033523473
   0.191848346945039
   0.133182862881598
   0.116049034622904
   0.102745309429078


rho_SA_h =

   1.0e-06 *

  -0.459053080088382
  -0.460370569872258
  -0.498605615416296
  -0.642833108550133
  -0.682091962941161
  -0.706793055445909


rho_h_h =

   1.0e-09 *

  -0.454213854637790
  -0.455984900239309
  -0.499870030989387
  -0.628337767293403
  -0.664021595759308
  -0.687367088752173

**Comment by dankelley** [comment]
Thanks, @PaulMBarker -- your new test values now work also in R (`develop` branch, commit 5995690c12b02c2a50b8482cb278661f9e531e45). I've put a note in the documentation of the R function alluding to the hope that the official documentation will be updated sometime in April 2017, so I am closing this issue now.
