### ISSUE TITLE
gsw_geo_strf_dyn_height() sometimes erroneously returns all zeros

### ISSUE THREAD

**Issue by dankelley** [TEOS-10/GSW-R#39]
```R
df <- structure(list(SA = c(36.855503939848, 36.4971650766637, 36.4977700026719,
36.2529246997542, 36.2534270655287, 36.002043110245, 36.0002357585083,
35.8278109198182, 35.8281142727647, 35.7015734367856, 35.7006709862616,
35.7848317547004, 35.7858367750849, 35.9496877557911, 35.9520999643311,
36.0623842502388, 36.0861726265337, 36.14217237462, 36.2275535176993,
36.2408756031207, 36.2187323903269, 36.1707742062984, 36.0918852617197,
35.9813688721453), CT = c(21.4947473754157, 16.6878140953016,
16.6748589933191, 14.5354547312802, 14.5417247209637, 13.1075384801307,
13.1059005757833, 11.9533561570296, 11.9365831694816, 10.834696340731,
10.8354205711472, 10.2515778760042, 10.2534330502052, 10.1594789517675,
10.1628546551997, 10.1319944946218, 10.000801742997, 9.97602409076545,
10.0160820710144, 9.89429410566537, 9.64473876660855, 9.23710853886353,
8.83733409331888, 8.23858450492611), p = c(11, 102.1, 103.1,
202.4, 202.4, 301, 301.6, 402.1, 403.1, 559.8, 560.5, 701.3,
701.4, 790.9, 791.3, 895.3, 943.4, 1046.5, 1137.4, 1193.3, 1242.6,
1292.7, 1345.1, 1405.4)), .Names = c("SA", "CT", "p"), row.names = c(NA,
-24L), class = "data.frame")
gsw::gsw_geo_strf_dyn_height(df$SA, df$CT, df$p)
```
yields
```
 [1] 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
```
although this profile (station `"19"` within `data(section)`, in the `oce` package) seems really very similar to the stations before and after it. Here's a plot of the station ... which seems ok to me.

<img width="837" alt="screen shot 2017-07-23 at 1 01 40 pm" src="https://user-images.githubusercontent.com/99469/28500896-1b26f3ac-6fa7-11e7-9746-ef335171f218.png">

**Comment by dankelley** [comment]
The problem is that two pressures are identical (as shown below). I don't agree that this (not-too-uncommon) condition should lead to the early return that is at line 3703 of the source (https://github.com/TEOS-10/GSW-R/blob/develop/src/gsw_oceanographic_toolbox.c#L3703) but it is clearly intentional.
```
      df.SA     df.CT   df.p dh
1  36.85550 21.494747   11.0  0
2  36.49717 16.687814  102.1  0
3  36.49777 16.674859  103.1  0
4  36.25292 14.535455  202.4  0
5  36.25343 14.541725  202.4  0
...
```

**Comment by efiring** [comment]
I handled this (non-monotonic pressure) in GSW-Python by raising an Exception in the wrapper.  I think that handling it in the C would be both arbitrary and complex--that function is already overly complex. Options for handling a sequence of repeats would be to use the first, or the last, or the average, or... And what about the case where bottle pressures are out of order?  Should the C somehow handle that, too?  Ideally, the C would catch the conditions it can't handle and signal the error; but leaving that responsibility to the wrapper is my workaround for now.  Here is another bit of code in my wrapper that handles limitations in the C:
```python
        # If p_ref is below the deepest value, skip the profile.
        pgood = p[ind][igood]
        # The C function calls the rr68 interpolation, which
        # requires at least 4 "bottles"; but the C function is
        # not checking this, so we need to do so.
        if  len(pgood) > 3 and pgood[-1] >= p_ref:
            dh[ind][igood] = _gsw_ufuncs.geo_strf_dyn_height(
                                         SA[ind][igood],
                                         CT[ind][igood],
                                         pgood, p_ref)
```

**Comment by dankelley** [comment]
Thanks for the note, Eric. I'm doing the same sort of thing in the R version, for the same reasons.

**Comment by dankelley** [comment]
I'm closing this now, since we have three tests that should take care of the cases that the underlying C code cannot handle. (In `oce::swDynamicHeight` I'll do some massaging to prevent these problems, when feasible.)
