### ISSUE TITLE
Official Listing on teos-10.org

### ISSUE THREAD

**Issue by PaulMBarker** [TEOS-10/GSW-R#44]
I am working on updating the software page on the TEOS10 website. I would like to add something to show that this package exists. How would you like this to appear?

Paul.

**Comment by dankelley** [comment]
Hi Paul.  I'm not sure what you mean.  Do you maybe want a paragraph with some links?  Or maybe something else?

As a first step, could you write the URL for the page to which you refer?

**Comment by dankelley** [comment]
Oh, I think you must mean the page http://teos-10.org/software.htm.  If you are still using button-style icons, it should say that it is based on gsw version 3.05-4 and not refer to downloading.  The word "Download" could be replaced by the word "CRAN link" and the action on clicking should take the user to https://cran.r-project.org/web/packages/gsw/index.html, which is the official website on CRAN, the Comprehensive R Archive Network website.

NOTE 1. The reason the text/button should not say "download" but rather "link" is that R does not work by having users downloading files.  Installation is done within R itself.  That way, R selects a version that is appropriate to the version of R and the machine architecture and OS type.  It also checks md5 sums to ensure that the file has not been altered, i.e. that the version as downloaded is indeed the version that CRAN accepted, meaning that it has got through a battery of tests on about 8 different machine/OS setups.

NOTE 2. The site I name above provides a link to a more user-friendly site at http://teos-10.github.io/GSW-R/index.html but that is not official, e.g. if gsw gets kicked off CRAN, the official site would disappear but the second one would still exist. Packages get kicked off if their test suites fail on the regular automated testing, which means if R, Fortran, C, etc change in a way that makes the code problematic, the package will be auto-deleted.

**Comment by PaulMBarker** [comment]
Hi Dan,
Sorry for the cryptic message, but yes I did mean that webpage.
I do not have to have buttons, I can easily add a paragraph if it suits you better, just let me know what you would like, It can even have multiple links. 
Eric Firing sent a couple of sentences for the python version, it has 2 links, one to the python version in the python website and the other to the teos10 github page.
Paul.

**Comment by dankelley** [comment]
@richardsc -- do you agree with the below phrasing, in response to @PaulMBarker's question?  If not, please add an additional comment in which you have revised text.  (I have written this in code format, so Paul can see the markings for typewriter font.)  I will be in meetings for the morning but will be able to check into this again in the afternoon.  I think it would be great to finalize this Paul by early next week ... OK, Paul?

```
R users can access TEOS-10 algorithms through the <tt>gsw</tt> package.  This
package is hosted on CRAN (the Comprehensive R Archive Network), and so it is
installed from within R itself, by typing <tt>install.packages('gsw')</tt> in
an R session.  The current <tt>gsw</tt> version (1.0-5) is based on
<tt>GSW-C</tt> version 3.0-5 (git commit
5b4d959e54031f9e972f3e863f63e67fa4f5bfec at https://github.com/TEOS-10/GSW-C).
The CRAN <tt>gsw</tt> web page,
https://cran.r-project.org/web/packages/gsw/index.html, provides check results,
an issue tracker, a reference manual, a vignette, and a link to a supplemental
webpage at http://teos-10.github.io/GSW-R/index.html.
```

**Comment by PaulMBarker** [comment]
Perfectly fine by me.
By the way, I have been told you typically come out of meetings dumber than you went in.

Paul.

**Comment by dankelley** [comment]
Oh, I like that comment on meetings!  Another thing is that the utility of meetings is an interesting function of the number of participants.  I think when an individual hits a roadblock, it helps to have 1 more person.  But adding another does not help, or at least the efficiency per person starts to drop quickly.  I've spent a lot of time over the past few years on a committee of 70 people (very hard to make real progress) and another of about 15 people of whom only 5 are mouthy like me (we can get stuff done).

**Comment by PaulMBarker** [comment]
Hey Dan and Richard,

On Monday I will update the teos-10 software website  http://www.teos-10.org/software.htm to include the new software and links could you please finalise and agree on how you would like it to appear.

Paul.

**Comment by dankelley** [comment]
For R, I propose the text I suggested previously, i.e.

```
R users can access TEOS-10 algorithms through the <tt>gsw</tt> package.  This
package is hosted on CRAN (the Comprehensive R Archive Network), and so it is
installed from within R itself, by typing <tt>install.packages('gsw')</tt> in
an R session.  The current <tt>gsw</tt> version (1.0-5) is based on
<tt>GSW-C</tt> version 3.0-5 (git commit
5b4d959e54031f9e972f3e863f63e67fa4f5bfec at https://github.com/TEOS-10/GSW-C).
The CRAN <tt>gsw</tt> web page,
https://cran.r-project.org/web/packages/gsw/index.html, provides check results,
an issue tracker, a reference manual, a vignette, and a link to a supplemental
webpage at http://teos-10.github.io/GSW-R/index.html.
```

**Comment by dankelley** [comment]
I'm about to add a new issue, and I see that this issue was addressed nearly a year ago, so I'm closing this.
