### ISSUE TITLE
Post release: tag a release and update webpage

### ISSUE THREAD

**Issue by richardsc** [TEOS-10/GSW-R#60]
Now that the package is on  CRAN, we should tag a release and update the docs site. For example, I noticed at least that the currently published site has a footnote that requires a manual update:

https://teos-10.github.io/GSW-R/articles/gsw.html#fn1

I'll take care of the former (release) if @dankelley can do the latter (blogdown site).

* [x] Create release from v1.1-1 tag
* [x] Update blogdown site

**Comment by dankelley** [comment]
Sounds good.  Note that what is on CRAN is not the same as what is presently on github.  I always forget to retag after fixing up for CRAN.

If you do 'git tag' you can find something that was (maybe) what eventually got into CRAN. But I am not good at remembering to tag, or to release.  (I'm not sure I truly see the point of either.  CRAN holds the exact source that made the binaries on CRAN, after all.  And I imagine every package starts getting changes very soon after a CRAN release, so I'm not sure why anyone would want to do a PR after the release version.)

I won't see email again until this aft.

**Comment by richardsc** [comment]
You made a tag yesterday for the version that was (I'm pretty sure) accepted to CRAN. I turned that into a release.
